### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by ansarizafar** [Urigo/merge-graphql-schemas#160] opened 2018-09-02 14:10 UTC
test.js exists on the correct location but I am still getting this strange error
````
{ Error: Cannot find module '/home/zafar/projects/framework/sapper-webpack/schema/resolvers/test.js'
    at webpackEmptyContext (webpack:///../webeo/node_modules/merge-graphql-schemas/dist_sync?:2:10)
    at eval (webpack:///../webeo/node_modules/merge-graphql-schemas/dist/index.esm.js?:3791:108)
    at Array.map (<anonymous>)
    at fileLoader (webpack:///../webeo/node_modules/merge-graphql-schemas/dist/index.esm.js?:3781:6)
    at module.exports (webpack:///../webeo/server/plugins/graphql.js?:15:32)
    at application.loadPlugins (webpack:///../webeo/server/application.js?:39:101)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3) code: 'MODULE_NOT_FOUND' }
````
Here is my code
```
let typeDefs = mergeTypes(fileLoader(path.join(process.cwd(), 'schema/types/*.graphql')), { all: true });
let resolvers = mergeResolvers(fileLoader(path.join(process.cwd(), 'schema/resolvers'),{ extensions: ['.js'] }), { all: true });
````
Type definition are loading correctly but revolvers are not. Is there any solution available for this issue?

**Comment by dan003400** [comment] 2018-09-07 02:44
Having the same issue.

Getting "Cannot find module" for a file that 100% exists.

Using this:
```
import path from 'path';
import { fileLoader, mergeResolvers } from 'merge-graphql-schemas';

const resolversArray = fileLoader(path.join(__dirname, './resolvers'));

export default mergeResolvers(resolversArray);
```

**Comment by cfnelson** [comment] 2018-09-11 23:49
@ansarizafar @dan003400 Would you happen to have a minimal reproduction of this. It will go a long way for us to understand what is happening and debug the problem.

**Comment by beeplin** [comment] 2018-09-15 04:14
Hey guys, I encountered the same issue and then found that was because I fogot to use `path.join(_dirname, xxx)`, so the `require(f)` in the `fileLoader` source code cannot find the correct path.

So for @ansarizafar maybe use `__dirname` instead of `process.cwd()` might help. Basically the `fileLoader` source code is quite straightforward and I guess the `cannot find module` is due to we fail to pass the correct file path to it.

**Comment by dan003400** [comment] 2018-09-19 18:06
Tried using `__dirname` and seeing same issue, it shows it is not able to find the module that does in fact exist.

**Comment by cfnelson** [comment] 2018-09-19 18:18
@dan003400 Have you checked that the build output contains the files in question? The folders/files will be in your project but depending on how your building/bundling your app the files in question might not be within the final build/bundle output. 

If this isn't the case than a min repo of this would go a long way to identifying the issue.

**Comment by ampProjects** [comment] 2019-05-04 09:52
Hi,
I have the same issue. 
When I use merge-schemas like this:

`const typeDefs = gql(mergeTypes(fileLoader(path.join(__dirname, 'schemas/'))));
const resolvers = mergeResolvers(fileLoader(path.join(__dirname, 'resolvers')));`

and try to compile it with webpack, all files in schemas and resolvers folder are not compiled. Webpack normally find "require" or "import" for making the compilation, but we don´t have that here. 
When you try to run the app, the bundle try to find those folders (schemas and resolvers) in dist folder where webpack compile bundles, but they are not.

Any suggestion how to fix this problems?

Thanks.

**Comment by ardatan** [comment] 2019-07-15 06:32
Using `fileLoader` and `webpack` together can cause this kind of issues similar to https://github.com/Urigo/merge-graphql-schemas/issues/202

Personally, I recommend you not to use webpack for NodeJS. But if you'd like to use it, it'd better to avoid using fileLoader. Otherwise, you need to copy those imported files into your output folder which makes using webpack a little pointless

**Closed by ardatan** 2019-07-15 06:32 UTC
Labels: 🎙️question
